#!/bin/bash

#Run python program
xterm -hold -e 'python mav_exchange.py | sleep 6' |

#Open mav_proxy and add new output
xterm -hold -e 'mavproxy.py --master tcp:127.0.0.1:5760 --sitl 127.0.0.1:5501 --out 127.0.0.1:14550 --out 127.0.0.1:14551' |

#Open apm planner
apmplanner2 &
